### ISSUE TITLE
Can not the labels be recovered for all frames?

### ISSUE THREAD

**Issue by finnSartoris** [JulesSanchez/recoverKITTI360label#1]
Thanks for the great work! I noticed that when creating labels (through recoverLabels.py) for a few frames of raw data no labels are recovered. Is this the way it is supposed to be? Or can not labels be created for those frames because there are no data_poses for them? 
For example in the sequence '2013_05_28_drive_0003_sync' no labels are created for the frame '0000000002'.

**Comment by JulesSanchez** [comment]
Hello finnSartoris,

Thank you for your interest. Indeed we don't gather labels for frame which doesn't have their positions available. If you look at the cam0_to_world associated to  '2013_05_28_drive_0003_sync', you can see that 2 is missing from it. As such we skip it.
Nevertheless, if you absolutely need to recover labels from such frames (as they are several) you could interpolate its position based on the closest positions available.

I hope I answered your question.

**Comment by finnSartoris** [comment]
Yes, thanks a lot!
